In [1]:
%load_ext cudf.pandas
import pandas as pd
import cupy as cp
import cudf

In [2]:
df = cudf.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
from cuml.preprocessing import MaxAbsScaler
from cuml.preprocessing import MinMaxScaler
from cuml.preprocessing import Normalizer
from cuml.preprocessing import RobustScaler
from cuml.preprocessing import StandardScaler
from cuml.preprocessing import Binarizer
from cuml.preprocessing import FunctionTransformer
from cuml.preprocessing import KBinsDiscretizer
import cupy as cp
import time

In [4]:
class Normalization(object):
    def __init__(self, dataset):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_numpy_array = self.dataset.copy().to_numpy()
        self.X = cp.array(self.dataset_numpy_array)


    def MaxAbsScaler(self):
        global maxAbsScaler_global

        transformer = MaxAbsScaler().fit(self.X)
        df_maxAbs_scaler_transform = transformer.transform(self.X)
        
        maxAbsScaler_global = cudf.DataFrame(df_maxAbs_scaler_transform)
    
    def MinMaxScaler(self):
        global MinMaxScaler_global

        transformer = MinMaxScaler().fit(self.X)
        df_MinMaxScaler_transform = transformer.transform(self.X)

        MinMaxScaler_global = cudf.DataFrame(df_MinMaxScaler_transform)

    def Normalizer(self):
        global normalizer_global

        transformer = Normalizer().fit(self.X)
        df_normalizer_transform = transformer.transform(self.X)

        normalizer_global = cudf.DataFrame(df_normalizer_transform)

    def RobustScaler(self):
        global robust_scaler_global

        transformer = RobustScaler().fit(self.X)
        df_robust_scaler_transform = transformer.transform(self.X)

        robust_scaler_global = cudf.DataFrame(df_robust_scaler_transform)

    def StandardScaler(self):
        global standard_scaler_global

        transformer = StandardScaler().fit(self.X)
        df_standard_scaler_transform = transformer.transform(self.X)

        standard_scaler_global = cudf.DataFrame(df_standard_scaler_transform)

    def Binarizer(self):
        global binarizer_global

        transformer = Binarizer().fit(self.X)
        df_binarizer_transform = transformer.transform(self.X)

        binarizer_global = cudf.DataFrame(df_binarizer_transform)

    def FunctionTransformer(self):
        global function_transformer_global

        transformer = FunctionTransformer(func=cp.log1p)
        df_function_transformer_transform = transformer.transform(self.X)

        function_transformer_global = cudf.DataFrame(df_function_transformer_transform)

    def KBinsDiscretizer(self):
        global KBinsDiscretizer_global

        transformer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit(self.X)
        df_KBinsDiscretizer_transform = transformer.transform(self.X)

        KBinsDiscretizer_global = cudf.DataFrame(df_KBinsDiscretizer_transform)


    def main(self):
        st = time.time()
        self.MaxAbsScaler()
        self.MinMaxScaler()
        self.Normalizer()
        self.RobustScaler()
        self.StandardScaler()
        self.Binarizer()
        self.FunctionTransformer()
        self.KBinsDiscretizer()

        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [5]:
norm = Normalization(df)

In [6]:
norm.main()

Execution time: 0.5135951042175293 seconds

In [7]:
maxAbsScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375
1,0.0,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125
2,0.0,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000
3,0.0,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750
4,0.0,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875
253676,0.0,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500
253677,0.0,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250
253678,0.0,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125
253679,1.0,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250

In [8]:
MinMaxScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.325581,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.00,0.6,0.500000,1.0,0.0,0.666667,0.6,0.285714
1,0.0,0.0,0.0,0.0,0.151163,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.50,0.0,0.000000,0.0,0.0,0.500000,1.0,0.000000
2,0.0,1.0,1.0,1.0,0.186047,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.00,1.0,1.000000,1.0,0.0,0.666667,0.6,1.000000
3,0.0,1.0,0.0,1.0,0.174419,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.833333,0.4,0.714286
4,0.0,1.0,1.0,1.0,0.139535,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.1,0.000000,0.0,0.0,0.833333,0.8,0.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.383721,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.166667,0.0,1.0,0.333333,1.0,0.857143
253676,0.0,1.0,1.0,1.0,0.069767,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.75,0.0,0.000000,1.0,0.0,0.833333,0.2,0.428571
253677,0.0,0.0,0.0,1.0,0.186047,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.083333,0.8,0.142857
253678,0.0,1.0,0.0,1.0,0.127907,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.000000,0.0,1.0,0.500000,0.8,0.000000
253679,1.0,1.0,1.0,1.0,0.151163,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.666667,1.0,0.142857

In [9]:
normalizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.00000,0.020911,0.020911,0.020911,0.836425,0.020911,0.0,0.000000,0.000000,0.000000,...,0.020911,0.000000,0.104553,0.376391,0.313659,0.020911,0.000000,0.188196,0.083642,0.062732
1,0.00000,0.000000,0.000000,0.000000,0.929760,0.037190,0.0,0.000000,0.037190,0.000000,...,0.000000,0.037190,0.111571,0.000000,0.000000,0.000000,0.000000,0.260333,0.223142,0.037190
2,0.00000,0.018976,0.018976,0.018976,0.531337,0.000000,0.0,0.000000,0.000000,0.018976,...,0.018976,0.018976,0.094882,0.569290,0.569290,0.018976,0.000000,0.170787,0.075905,0.151811
3,0.00000,0.033241,0.000000,0.033241,0.897510,0.000000,0.0,0.000000,0.033241,0.033241,...,0.033241,0.000000,0.066482,0.000000,0.000000,0.000000,0.000000,0.365652,0.099723,0.199447
4,0.00000,0.036322,0.036322,0.036322,0.871719,0.000000,0.0,0.000000,0.036322,0.036322,...,0.036322,0.000000,0.072643,0.108965,0.000000,0.000000,0.000000,0.399538,0.181608,0.145287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.00000,0.021437,0.021437,0.021437,0.964680,0.000000,0.0,0.000000,0.000000,0.021437,...,0.021437,0.000000,0.064312,0.000000,0.107187,0.000000,0.021437,0.107187,0.128624,0.150061
253676,0.00000,0.045175,0.045175,0.045175,0.813157,0.000000,0.0,0.090351,0.000000,0.000000,...,0.045175,0.000000,0.180702,0.000000,0.000000,0.045175,0.000000,0.496929,0.090351,0.180702
253677,0.00000,0.000000,0.000000,0.034879,0.976612,0.000000,0.0,0.000000,0.034879,0.034879,...,0.034879,0.000000,0.034879,0.000000,0.000000,0.000000,0.000000,0.069758,0.174395,0.069758
253678,0.00000,0.040193,0.000000,0.040193,0.924448,0.000000,0.0,0.000000,0.000000,0.040193,...,0.040193,0.000000,0.120580,0.000000,0.000000,0.000000,0.040193,0.281354,0.200967,0.040193
253679,0.03625,0.036250,0.036250,0.036250,0.906249,0.000000,0.0,0.072500,0.036250,0.036250,...,0.036250,0.000000,0.072500,0.000000,0.000000,0.000000,0.000000,0.326250,0.217500,0.072500

In [10]:
robust_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,0.0,1.857143,1.0,0.0,0.0,-1.0,-1.0,...,0.0,0.0,3.0,9.0,5.000000,1.0,0.0,0.25,-0.5,-1.333333
1,0.0,0.0,0.0,-1.0,-0.285714,1.0,0.0,0.0,0.0,-1.0,...,-1.0,1.0,1.0,0.0,0.000000,0.0,0.0,-0.25,0.5,-2.000000
2,0.0,1.0,1.0,0.0,0.142857,0.0,0.0,0.0,-1.0,0.0,...,0.0,1.0,3.0,15.0,10.000000,1.0,0.0,0.25,-0.5,0.333333
3,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.75,-1.0,-0.333333
4,0.0,1.0,1.0,0.0,-0.428571,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.5,0.000000,0.0,0.0,0.75,0.0,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,0.0,2.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,1.666667,0.0,1.0,-0.75,0.5,0.000000
253676,0.0,1.0,1.0,0.0,-1.285714,0.0,0.0,2.0,-1.0,-1.0,...,0.0,0.0,2.0,0.0,0.000000,1.0,0.0,0.75,-1.5,-1.000000
253677,0.0,0.0,0.0,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,0.0,0.000000,0.0,0.0,-1.50,0.0,-1.666667
253678,0.0,1.0,0.0,0.0,-0.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,0.000000,0.0,1.0,-0.25,0.0,-2.000000
253679,1.0,1.0,1.0,0.0,-0.285714,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.25,0.5,-1.666667

In [11]:
standard_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-0.322458,1.153688,1.165254,0.196922,1.757936,1.120927,-0.205637,-0.425292,-1.762814,-1.316872,...,0.226863,-0.303173,2.329121,1.998592,1.233999,2.223615,-0.887021,0.316900,-1.065595,-1.474487
1,-0.322458,-0.866785,-0.858182,-5.078164,-0.511806,1.120927,-0.205637,-0.425292,0.567275,-1.316872,...,-4.407954,3.298445,0.457294,-0.429630,-0.486592,-0.449718,-0.887021,-0.337933,0.963272,-2.440138
2,-0.322458,1.153688,1.165254,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,3.298445,2.329121,3.617407,2.954590,2.223615,-0.887021,0.316900,-1.065595,0.939638
3,-0.322458,1.153688,-0.858182,0.196922,-0.209174,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.971733,-2.080028,-0.026012
4,-0.322458,1.153688,1.165254,0.196922,-0.663122,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.024926,-0.486592,-0.449718,-0.887021,0.971733,-0.051162,-0.991662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,-0.322458,1.153688,1.165254,0.196922,2.514516,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,0.086938,-0.449718,1.127369,-0.992766,0.963272,0.456813
253676,-0.322458,1.153688,1.165254,0.196922,-1.571019,-0.892119,-0.205637,2.439387,-1.762814,-1.316872,...,0.226863,-0.303173,1.393207,-0.429630,-0.486592,2.223615,-0.887021,0.971733,-3.094461,-0.991662
253677,-0.322458,-0.866785,-0.858182,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-1.414532,-0.429630,-0.486592,-0.449718,-0.887021,-1.975015,-0.051162,-1.957312
253678,-0.322458,1.153688,-0.858182,0.196922,-0.814438,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,-0.486592,-0.449718,1.127369,-0.337933,-0.051162,-2.440138
253679,3.101183,1.153688,1.165254,0.196922,-0.511806,-0.892119,-0.205637,2.439387,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.316900,0.963272,-1.957312

In [12]:
binarizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0
253676,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0
253677,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
253678,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
253679,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0

In [13]:
function_transformer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.000000,0.693147,0.693147,0.693147,3.713572,0.693147,0.0,0.000000,0.000000,0.000000,...,0.693147,0.000000,1.791759,2.944439,2.772589,0.693147,0.000000,2.302585,1.609438,1.386294
1,0.000000,0.000000,0.000000,0.000000,3.258097,0.693147,0.0,0.000000,0.693147,0.000000,...,0.000000,0.693147,1.386294,0.000000,0.000000,0.000000,0.000000,2.079442,1.945910,0.693147
2,0.000000,0.693147,0.693147,0.693147,3.367296,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.693147,1.791759,3.433987,3.433987,0.693147,0.000000,2.302585,1.609438,2.197225
3,0.000000,0.693147,0.000000,0.693147,3.332205,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.484907,1.386294,1.945910
4,0.000000,0.693147,0.693147,0.693147,3.218876,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,1.386294,0.000000,0.000000,0.000000,2.484907,1.791759,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.000000,0.693147,0.693147,0.693147,3.828641,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,1.791759,0.000000,0.693147,1.791759,1.945910,2.079442
253676,0.000000,0.693147,0.693147,0.693147,2.944439,0.000000,0.0,1.098612,0.000000,0.000000,...,0.693147,0.000000,1.609438,0.000000,0.000000,0.693147,0.000000,2.484907,1.098612,1.609438
253677,0.000000,0.000000,0.000000,0.693147,3.367296,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,1.098612,1.791759,1.098612
253678,0.000000,0.693147,0.000000,0.693147,3.178054,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,0.000000,0.000000,0.693147,2.079442,1.791759,0.693147
253679,0.693147,0.693147,0.693147,0.693147,3.258097,0.000000,0.0,1.098612,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.302585,1.945910,1.098612

In [14]:
KBinsDiscretizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0,2,2,2,0,2,0,0,0,0,...,2,0,2,1,1,2,0,2,1,0
1,0,0,0,0,0,2,0,0,2,0,...,0,2,1,0,0,0,0,1,2,0
2,0,2,2,2,0,0,0,0,0,2,...,2,2,2,2,2,2,0,2,1,2
3,0,2,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,1,2
4,0,2,2,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,2,2,2,1,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,2
253676,0,2,2,2,0,0,0,2,0,0,...,2,0,2,0,0,2,0,2,0,1
253677,0,0,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,0,2,0
253678,0,2,0,2,0,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,0
253679,2,2,2,2,0,0,0,2,2,2,...,2,0,0,0,0,0,0,2,2,0

In [15]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = cp.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = cp.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = cp.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = cp.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = cp.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = cp.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = cudf.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        self.generating_data()
        self.generating_dataframe()

In [16]:
gen_df = Data_Generation(df, 10000000, float)

In [17]:
gen_df.main()

In [18]:
generated_data_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,87.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,3.0,14.0,27.0,1.0,1.0,10.0,4.0,8.0
1,1.0,1.0,0.0,93.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,5.0,11.0,0.0,0.0,3.0,4.0,6.0
2,0.0,1.0,0.0,72.0,1.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,1.0,12.0,5.0,0.0,1.0,7.0,1.0,3.0
3,0.0,0.0,1.0,62.0,1.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,5.0,23.0,8.0,1.0,0.0,13.0,4.0,3.0
4,0.0,0.0,1.0,43.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,2.0,7.0,17.0,0.0,0.0,1.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,54.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,4.0,5.0,6.0,1.0,1.0,11.0,6.0,6.0
9999996,1.0,1.0,1.0,91.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,1.0,4.0,30.0,19.0,1.0,1.0,7.0,4.0,1.0
9999997,0.0,0.0,1.0,64.0,1.0,0.0,2.0,1.0,1.0,1.0,...,0.0,0.0,2.0,11.0,25.0,0.0,1.0,10.0,3.0,6.0
9999998,0.0,1.0,0.0,51.0,1.0,1.0,2.0,0.0,1.0,1.0,...,0.0,0.0,4.0,6.0,28.0,1.0,0.0,12.0,5.0,2.0
9999999,1.0,0.0,0.0,47.0,1.0,0.0,2.0,0.0,1.0,1.0,...,0.0,1.0,4.0,0.0,7.0,1.0,1.0,11.0,5.0,3.0

In [19]:
norm_gen_data = Normalization(generated_data_global)

In [20]:
norm_gen_data.main()

Execution time: 9.14775800704956 seconds

In [21]:
maxAbsScaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.0,1.0,1.0,0.887755,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.6,0.466667,0.900000,1.0,1.0,0.769231,0.666667,1.000
1,1.0,1.0,0.0,0.948980,1.0,0.0,0.5,1.0,0.0,0.0,...,0.0,1.0,0.2,0.166667,0.366667,0.0,0.0,0.230769,0.666667,0.750
2,0.0,1.0,0.0,0.734694,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.2,0.400000,0.166667,0.0,1.0,0.538462,0.166667,0.375
3,0.0,0.0,1.0,0.632653,1.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.766667,0.266667,1.0,0.0,1.000000,0.666667,0.375
4,0.0,0.0,1.0,0.438776,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.4,0.233333,0.566667,0.0,0.0,0.076923,0.166667,0.875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,0.551020,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.8,0.166667,0.200000,1.0,1.0,0.846154,1.000000,0.750
9999996,1.0,1.0,1.0,0.928571,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.8,1.000000,0.633333,1.0,1.0,0.538462,0.666667,0.125
9999997,0.0,0.0,1.0,0.653061,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.4,0.366667,0.833333,0.0,1.0,0.769231,0.500000,0.750
9999998,0.0,1.0,0.0,0.520408,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.8,0.200000,0.933333,1.0,0.0,0.923077,0.833333,0.250
9999999,1.0,0.0,0.0,0.479592,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.8,0.000000,0.233333,1.0,1.0,0.846154,0.833333,0.375

In [22]:
MinMaxScaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.0,1.0,1.0,0.872093,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.50,0.466667,0.900000,1.0,1.0,0.750000,0.6,1.000000
1,1.0,1.0,0.0,0.941860,1.0,0.0,0.5,1.0,0.0,0.0,...,0.0,1.0,0.00,0.166667,0.366667,0.0,0.0,0.166667,0.6,0.714286
2,0.0,1.0,0.0,0.697674,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.00,0.400000,0.166667,0.0,1.0,0.500000,0.0,0.285714
3,0.0,0.0,1.0,0.581395,1.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.00,0.766667,0.266667,1.0,0.0,1.000000,0.6,0.285714
4,0.0,0.0,1.0,0.360465,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.25,0.233333,0.566667,0.0,0.0,0.000000,0.0,0.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,0.488372,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.75,0.166667,0.200000,1.0,1.0,0.833333,1.0,0.714286
9999996,1.0,1.0,1.0,0.918605,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.75,1.000000,0.633333,1.0,1.0,0.500000,0.6,0.000000
9999997,0.0,0.0,1.0,0.604651,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.25,0.366667,0.833333,0.0,1.0,0.750000,0.4,0.714286
9999998,0.0,1.0,0.0,0.453488,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.75,0.200000,0.933333,1.0,0.0,0.916667,0.8,0.142857
9999999,1.0,0.0,0.0,0.406977,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.75,0.000000,0.233333,1.0,1.0,0.833333,0.8,0.285714

In [23]:
normalizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.010725,0.010725,0.010725,0.933113,0.010725,0.010725,0.000000,0.010725,0.000000,0.010725,...,0.000000,0.010725,0.032176,0.150156,0.289587,0.010725,0.010725,0.107254,0.042902,0.085804
1,0.010621,0.010621,0.000000,0.987798,0.010621,0.000000,0.010621,0.010621,0.000000,0.000000,...,0.000000,0.010621,0.010621,0.053107,0.116836,0.000000,0.000000,0.031864,0.042486,0.063729
2,0.000000,0.013582,0.000000,0.977896,0.013582,0.000000,0.027164,0.000000,0.000000,0.013582,...,0.000000,0.000000,0.013582,0.162983,0.067909,0.000000,0.013582,0.095073,0.013582,0.040746
3,0.000000,0.000000,0.014644,0.907944,0.014644,0.014644,0.000000,0.000000,0.014644,0.014644,...,0.000000,0.014644,0.073221,0.336818,0.117154,0.014644,0.000000,0.190375,0.058577,0.043933
4,0.000000,0.000000,0.021101,0.907326,0.000000,0.000000,0.000000,0.021101,0.000000,0.000000,...,0.021101,0.021101,0.042201,0.147704,0.358710,0.000000,0.000000,0.021101,0.021101,0.147704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,0.017700,0.000000,0.017700,0.955790,0.000000,0.000000,0.000000,0.000000,0.017700,0.000000,...,0.000000,0.017700,0.070799,0.088499,0.106199,0.017700,0.017700,0.194698,0.106199,0.106199
9999996,0.010188,0.010188,0.010188,0.927125,0.000000,0.000000,0.020376,0.000000,0.000000,0.000000,...,0.000000,0.010188,0.040753,0.305645,0.193575,0.010188,0.010188,0.071317,0.040753,0.010188
9999997,0.000000,0.000000,0.014139,0.904916,0.014139,0.000000,0.028279,0.014139,0.014139,0.014139,...,0.000000,0.000000,0.028279,0.155532,0.353483,0.000000,0.014139,0.141393,0.042418,0.084836
9999998,0.000000,0.016618,0.000000,0.847532,0.016618,0.016618,0.033237,0.000000,0.016618,0.016618,...,0.000000,0.000000,0.066473,0.099710,0.465311,0.016618,0.000000,0.199419,0.083091,0.033237
9999999,0.020240,0.000000,0.000000,0.951292,0.020240,0.000000,0.040481,0.000000,0.020240,0.020240,...,0.000000,0.020240,0.080961,0.000000,0.141682,0.020240,0.020240,0.222643,0.101201,0.060721

In [24]:
robust_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.0,1.0,1.0,0.727273,1.0,1.0,-0.5,0.0,-1.0,1.0,...,0.0,0.0,0.0,-0.0625,0.7500,0.0,1.0,0.500000,0.000000,1.000000
1,1.0,1.0,0.0,0.863636,1.0,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,-1.0,-0.6250,-0.2500,-1.0,0.0,-0.666667,0.000000,0.333333
2,0.0,1.0,0.0,0.386364,1.0,0.0,0.5,-1.0,-1.0,1.0,...,0.0,-1.0,-1.0,-0.1875,-0.6250,-1.0,1.0,0.000000,-1.000000,-0.666667
3,0.0,0.0,1.0,0.159091,1.0,1.0,-0.5,-1.0,0.0,1.0,...,0.0,0.0,1.0,0.5000,-0.4375,0.0,0.0,1.000000,0.000000,-0.666667
4,0.0,0.0,1.0,-0.272727,0.0,0.0,-0.5,0.0,-1.0,0.0,...,1.0,0.0,-0.5,-0.5000,0.1250,-1.0,0.0,-1.000000,-1.000000,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,-0.022727,0.0,0.0,-0.5,-1.0,0.0,0.0,...,0.0,0.0,0.5,-0.6250,-0.5625,0.0,1.0,0.666667,0.666667,0.333333
9999996,1.0,1.0,1.0,0.818182,0.0,0.0,0.5,-1.0,-1.0,0.0,...,0.0,0.0,0.5,0.9375,0.2500,0.0,1.0,0.000000,0.000000,-1.333333
9999997,0.0,0.0,1.0,0.204545,1.0,0.0,0.5,0.0,0.0,1.0,...,0.0,-1.0,-0.5,-0.2500,0.6250,-1.0,1.0,0.500000,-0.333333,0.333333
9999998,0.0,1.0,0.0,-0.090909,1.0,1.0,0.5,-1.0,0.0,1.0,...,0.0,-1.0,0.5,-0.5625,0.8125,0.0,0.0,0.833333,0.333333,-1.000000
9999999,1.0,0.0,0.0,-0.181818,1.0,0.0,0.5,-1.0,0.0,1.0,...,0.0,0.0,0.5,-0.9375,-0.5000,0.0,1.0,0.666667,0.333333,-0.666667

In [25]:
standard_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.00044,1.000514,1.000651,1.275139,1.000075,1.00035,-1.224644,0.999526,-1.000194,1.000594,...,-0.999923,0.999798,0.000002,-0.111340,1.341088,0.999753,1.000077,0.802242,0.292549,1.527800
1,1.00044,1.000514,-0.999349,1.514085,1.000075,-0.99965,0.000104,0.999526,-1.000194,-0.999407,...,-0.999923,0.999798,-1.414379,-1.117469,-0.447691,-1.000247,-0.999923,-1.068900,0.292549,0.654786
2,-0.99956,1.000514,-0.999349,0.677775,1.000075,-0.99965,1.224852,-1.000474,-1.000194,1.000594,...,-0.999923,-1.000202,-1.414379,-0.334924,-1.118483,-1.000247,1.000077,0.000324,-1.464518,-0.654735
3,-0.99956,-0.999487,1.000651,0.279533,1.000075,1.00035,-1.224644,-1.000474,0.999806,1.000594,...,-0.999923,0.999798,1.414382,0.894790,-0.783087,0.999753,-0.999923,1.604159,0.292549,-0.654735
4,-0.99956,-0.999487,1.000651,-0.477128,-0.999925,-0.99965,-1.224644,0.999526,-1.000194,-0.999407,...,1.000077,0.999798,-0.707189,-0.893885,0.223101,-1.000247,-0.999923,-1.603512,-1.464518,1.091293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.00044,-0.999487,1.000651,-0.039061,-0.999925,-0.99965,-1.224644,-1.000474,0.999806,-0.999407,...,-0.999923,0.999798,0.707192,-1.117469,-1.006684,0.999753,1.000077,1.069548,1.463928,0.654786
9999996,1.00044,1.000514,1.000651,1.434436,-0.999925,-0.99965,1.224852,-1.000474,-1.000194,-0.999407,...,-0.999923,0.999798,0.707192,1.677335,0.446699,0.999753,1.000077,0.000324,0.292549,-1.527749
9999997,-0.99956,-0.999487,1.000651,0.359181,1.000075,-0.99965,1.224852,0.999526,0.999806,1.000594,...,-0.999923,-1.000202,-0.707189,-0.446716,1.117491,-1.000247,1.000077,0.802242,-0.293140,0.654786
9999998,-0.99956,1.000514,-0.999349,-0.158534,1.000075,1.00035,1.224852,-1.000474,0.999806,1.000594,...,-0.999923,-1.000202,0.707192,-1.005677,1.452887,0.999753,-0.999923,1.336854,0.878238,-1.091242
9999999,1.00044,-0.999487,-0.999349,-0.317831,1.000075,-0.99965,1.224852,-1.000474,0.999806,1.000594,...,-0.999923,0.999798,0.707192,-1.676430,-0.894885,0.999753,1.000077,1.069548,0.878238,-0.654735

In [26]:
binarizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0
2,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
3,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
9999996,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
9999997,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
9999998,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
9999999,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0

In [27]:
function_transformer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.693147,0.693147,0.693147,4.477337,0.693147,0.693147,0.000000,0.693147,0.000000,0.693147,...,0.000000,0.693147,1.386294,2.708050,3.332205,0.693147,0.693147,2.397895,1.609438,2.197225
1,0.693147,0.693147,0.000000,4.543295,0.693147,0.000000,0.693147,0.693147,0.000000,0.000000,...,0.000000,0.693147,0.693147,1.791759,2.484907,0.000000,0.000000,1.386294,1.609438,1.945910
2,0.000000,0.693147,0.000000,4.290459,0.693147,0.000000,1.098612,0.000000,0.000000,0.693147,...,0.000000,0.000000,0.693147,2.564949,1.791759,0.000000,0.693147,2.079442,0.693147,1.386294
3,0.000000,0.000000,0.693147,4.143135,0.693147,0.693147,0.000000,0.000000,0.693147,0.693147,...,0.000000,0.693147,1.791759,3.178054,2.197225,0.693147,0.000000,2.639057,1.609438,1.386294
4,0.000000,0.000000,0.693147,3.784190,0.000000,0.000000,0.000000,0.693147,0.000000,0.000000,...,0.693147,0.693147,1.098612,2.079442,2.890372,0.000000,0.000000,0.693147,0.693147,2.079442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,0.693147,0.000000,0.693147,4.007333,0.000000,0.000000,0.000000,0.000000,0.693147,0.000000,...,0.000000,0.693147,1.609438,1.791759,1.945910,0.693147,0.693147,2.484907,1.945910,1.945910
9999996,0.693147,0.693147,0.693147,4.521789,0.000000,0.000000,1.098612,0.000000,0.000000,0.000000,...,0.000000,0.693147,1.609438,3.433987,2.995732,0.693147,0.693147,2.079442,1.609438,0.693147
9999997,0.000000,0.000000,0.693147,4.174387,0.693147,0.000000,1.098612,0.693147,0.693147,0.693147,...,0.000000,0.000000,1.098612,2.484907,3.258097,0.000000,0.693147,2.397895,1.386294,1.945910
9999998,0.000000,0.693147,0.000000,3.951244,0.693147,0.693147,1.098612,0.000000,0.693147,0.693147,...,0.000000,0.000000,1.609438,1.945910,3.367296,0.693147,0.000000,2.564949,1.791759,1.098612
9999999,0.693147,0.000000,0.000000,3.871201,0.693147,0.000000,1.098612,0.000000,0.693147,0.693147,...,0.000000,0.693147,1.609438,0.000000,2.079442,0.693147,0.693147,2.484907,1.791759,1.386294

In [28]:
KBinsDiscretizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,2,2,2,2,2,2,0,2,0,2,...,0,2,1,1,2,2,2,2,1,2
1,2,2,0,2,2,0,1,2,0,0,...,0,2,0,0,1,0,0,0,1,2
2,0,2,0,2,2,0,2,0,0,2,...,0,0,0,1,0,0,2,1,0,0
3,0,0,2,1,2,2,0,0,2,2,...,0,2,2,2,0,2,0,2,1,0
4,0,0,2,1,0,0,0,2,0,0,...,2,2,0,0,1,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,2,0,2,1,0,0,0,0,2,0,...,0,2,2,0,0,2,2,2,2,2
9999996,2,2,2,2,0,0,2,0,0,0,...,0,2,2,2,1,2,2,1,1,0
9999997,0,0,2,1,2,0,2,2,2,2,...,0,0,0,1,2,0,2,2,1,2
9999998,0,2,0,1,2,2,2,0,2,2,...,0,0,2,0,2,2,0,2,2,0
9999999,2,0,0,1,2,0,2,0,2,2,...,0,2,2,0,0,2,2,2,2,0