In [1]:
%load_ext cudf.pandas
import pandas as pd
import cupy as cp
import cudf
import cuml

In [2]:
df = cudf.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
from cuml.preprocessing import MaxAbsScaler
from cuml.preprocessing import MinMaxScaler
from cuml.preprocessing import Normalizer
from cuml.preprocessing import RobustScaler
from cuml.preprocessing import StandardScaler
from cuml.preprocessing import Binarizer
from cuml.preprocessing import FunctionTransformer
from cuml.preprocessing import KBinsDiscretizer
import cupy as cp
import time

In [4]:
class Normalization(object):
    def __init__(self, dataset):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_numpy_array = self.dataset.copy().to_numpy()
        self.X = cp.array(self.dataset_numpy_array)


    def MaxAbsScaler(self):
        global maxAbsScaler_global

        transformer = MaxAbsScaler().fit(self.X)
        df_maxAbs_scaler_transform = transformer.transform(self.X)
        
        maxAbsScaler_global = cudf.DataFrame(df_maxAbs_scaler_transform)
    
    def MinMaxScaler(self):
        global MinMaxScaler_global

        transformer = MinMaxScaler().fit(self.X)
        df_MinMaxScaler_transform = transformer.transform(self.X)

        MinMaxScaler_global = cudf.DataFrame(df_MinMaxScaler_transform)

    def Normalizer(self):
        global normalizer_global

        transformer = Normalizer().fit(self.X)
        df_normalizer_transform = transformer.transform(self.X)

        normalizer_global = cudf.DataFrame(df_normalizer_transform)

    def RobustScaler(self):
        global robust_scaler_global

        transformer = RobustScaler().fit(self.X)
        df_robust_scaler_transform = transformer.transform(self.X)

        robust_scaler_global = cudf.DataFrame(df_robust_scaler_transform)

    def StandardScaler(self):
        global standard_scaler_global

        transformer = StandardScaler().fit(self.X)
        df_standard_scaler_transform = transformer.transform(self.X)

        standard_scaler_global = cudf.DataFrame(df_standard_scaler_transform)

    def Binarizer(self):
        global binarizer_global

        transformer = Binarizer().fit(self.X)
        df_binarizer_transform = transformer.transform(self.X)

        binarizer_global = cudf.DataFrame(df_binarizer_transform)

    def FunctionTransformer(self):
        global function_transformer_global

        transformer = FunctionTransformer(func=cp.log1p)
        df_function_transformer_transform = transformer.transform(self.X)

        function_transformer_global = cudf.DataFrame(df_function_transformer_transform)

    def KBinsDiscretizer(self):
        global KBinsDiscretizer_global

        transformer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit(self.X)
        df_KBinsDiscretizer_transform = transformer.transform(self.X)

        KBinsDiscretizer_global = cudf.DataFrame(df_KBinsDiscretizer_transform)


    def main(self):
        st = time.time()
        self.MaxAbsScaler()
        self.MinMaxScaler()
        self.Normalizer()
        self.RobustScaler()
        self.StandardScaler()
        self.Binarizer()
        self.FunctionTransformer()
        self.KBinsDiscretizer()

        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [5]:
norm = Normalization(df)

In [6]:
norm.main()

Execution time: 0.5320963859558105 seconds

In [7]:
maxAbsScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375
1,0.0,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125
2,0.0,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000
3,0.0,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750
4,0.0,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875
253676,0.0,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500
253677,0.0,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250
253678,0.0,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125
253679,1.0,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250

In [8]:
MinMaxScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.325581,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.00,0.6,0.500000,1.0,0.0,0.666667,0.6,0.285714
1,0.0,0.0,0.0,0.0,0.151163,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.50,0.0,0.000000,0.0,0.0,0.500000,1.0,0.000000
2,0.0,1.0,1.0,1.0,0.186047,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.00,1.0,1.000000,1.0,0.0,0.666667,0.6,1.000000
3,0.0,1.0,0.0,1.0,0.174419,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.833333,0.4,0.714286
4,0.0,1.0,1.0,1.0,0.139535,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.1,0.000000,0.0,0.0,0.833333,0.8,0.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.383721,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.166667,0.0,1.0,0.333333,1.0,0.857143
253676,0.0,1.0,1.0,1.0,0.069767,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.75,0.0,0.000000,1.0,0.0,0.833333,0.2,0.428571
253677,0.0,0.0,0.0,1.0,0.186047,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.083333,0.8,0.142857
253678,0.0,1.0,0.0,1.0,0.127907,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.000000,0.0,1.0,0.500000,0.8,0.000000
253679,1.0,1.0,1.0,1.0,0.151163,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.666667,1.0,0.142857

In [9]:
normalizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.00000,0.020911,0.020911,0.020911,0.836425,0.020911,0.0,0.000000,0.000000,0.000000,...,0.020911,0.000000,0.104553,0.376391,0.313659,0.020911,0.000000,0.188196,0.083642,0.062732
1,0.00000,0.000000,0.000000,0.000000,0.929760,0.037190,0.0,0.000000,0.037190,0.000000,...,0.000000,0.037190,0.111571,0.000000,0.000000,0.000000,0.000000,0.260333,0.223142,0.037190
2,0.00000,0.018976,0.018976,0.018976,0.531337,0.000000,0.0,0.000000,0.000000,0.018976,...,0.018976,0.018976,0.094882,0.569290,0.569290,0.018976,0.000000,0.170787,0.075905,0.151811
3,0.00000,0.033241,0.000000,0.033241,0.897510,0.000000,0.0,0.000000,0.033241,0.033241,...,0.033241,0.000000,0.066482,0.000000,0.000000,0.000000,0.000000,0.365652,0.099723,0.199447
4,0.00000,0.036322,0.036322,0.036322,0.871719,0.000000,0.0,0.000000,0.036322,0.036322,...,0.036322,0.000000,0.072643,0.108965,0.000000,0.000000,0.000000,0.399538,0.181608,0.145287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.00000,0.021437,0.021437,0.021437,0.964680,0.000000,0.0,0.000000,0.000000,0.021437,...,0.021437,0.000000,0.064312,0.000000,0.107187,0.000000,0.021437,0.107187,0.128624,0.150061
253676,0.00000,0.045175,0.045175,0.045175,0.813157,0.000000,0.0,0.090351,0.000000,0.000000,...,0.045175,0.000000,0.180702,0.000000,0.000000,0.045175,0.000000,0.496929,0.090351,0.180702
253677,0.00000,0.000000,0.000000,0.034879,0.976612,0.000000,0.0,0.000000,0.034879,0.034879,...,0.034879,0.000000,0.034879,0.000000,0.000000,0.000000,0.000000,0.069758,0.174395,0.069758
253678,0.00000,0.040193,0.000000,0.040193,0.924448,0.000000,0.0,0.000000,0.000000,0.040193,...,0.040193,0.000000,0.120580,0.000000,0.000000,0.000000,0.040193,0.281354,0.200967,0.040193
253679,0.03625,0.036250,0.036250,0.036250,0.906249,0.000000,0.0,0.072500,0.036250,0.036250,...,0.036250,0.000000,0.072500,0.000000,0.000000,0.000000,0.000000,0.326250,0.217500,0.072500

In [10]:
robust_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,0.0,1.857143,1.0,0.0,0.0,-1.0,-1.0,...,0.0,0.0,3.0,9.0,5.000000,1.0,0.0,0.25,-0.5,-1.333333
1,0.0,0.0,0.0,-1.0,-0.285714,1.0,0.0,0.0,0.0,-1.0,...,-1.0,1.0,1.0,0.0,0.000000,0.0,0.0,-0.25,0.5,-2.000000
2,0.0,1.0,1.0,0.0,0.142857,0.0,0.0,0.0,-1.0,0.0,...,0.0,1.0,3.0,15.0,10.000000,1.0,0.0,0.25,-0.5,0.333333
3,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.75,-1.0,-0.333333
4,0.0,1.0,1.0,0.0,-0.428571,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.5,0.000000,0.0,0.0,0.75,0.0,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,0.0,2.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,1.666667,0.0,1.0,-0.75,0.5,0.000000
253676,0.0,1.0,1.0,0.0,-1.285714,0.0,0.0,2.0,-1.0,-1.0,...,0.0,0.0,2.0,0.0,0.000000,1.0,0.0,0.75,-1.5,-1.000000
253677,0.0,0.0,0.0,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,0.0,0.000000,0.0,0.0,-1.50,0.0,-1.666667
253678,0.0,1.0,0.0,0.0,-0.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,0.000000,0.0,1.0,-0.25,0.0,-2.000000
253679,1.0,1.0,1.0,0.0,-0.285714,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.25,0.5,-1.666667

In [11]:
standard_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-0.322458,1.153688,1.165254,0.196922,1.757936,1.120927,-0.205637,-0.425292,-1.762814,-1.316872,...,0.226863,-0.303173,2.329121,1.998592,1.233999,2.223615,-0.887021,0.316900,-1.065595,-1.474487
1,-0.322458,-0.866785,-0.858182,-5.078164,-0.511806,1.120927,-0.205637,-0.425292,0.567275,-1.316872,...,-4.407954,3.298445,0.457294,-0.429630,-0.486592,-0.449718,-0.887021,-0.337933,0.963272,-2.440138
2,-0.322458,1.153688,1.165254,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,3.298445,2.329121,3.617407,2.954590,2.223615,-0.887021,0.316900,-1.065595,0.939638
3,-0.322458,1.153688,-0.858182,0.196922,-0.209174,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.971733,-2.080028,-0.026012
4,-0.322458,1.153688,1.165254,0.196922,-0.663122,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.024926,-0.486592,-0.449718,-0.887021,0.971733,-0.051162,-0.991662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,-0.322458,1.153688,1.165254,0.196922,2.514516,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,0.086938,-0.449718,1.127369,-0.992766,0.963272,0.456813
253676,-0.322458,1.153688,1.165254,0.196922,-1.571019,-0.892119,-0.205637,2.439387,-1.762814,-1.316872,...,0.226863,-0.303173,1.393207,-0.429630,-0.486592,2.223615,-0.887021,0.971733,-3.094461,-0.991662
253677,-0.322458,-0.866785,-0.858182,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-1.414532,-0.429630,-0.486592,-0.449718,-0.887021,-1.975015,-0.051162,-1.957312
253678,-0.322458,1.153688,-0.858182,0.196922,-0.814438,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,-0.486592,-0.449718,1.127369,-0.337933,-0.051162,-2.440138
253679,3.101183,1.153688,1.165254,0.196922,-0.511806,-0.892119,-0.205637,2.439387,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.316900,0.963272,-1.957312

In [12]:
binarizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0
253676,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0
253677,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
253678,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
253679,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0

In [13]:
function_transformer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.000000,0.693147,0.693147,0.693147,3.713572,0.693147,0.0,0.000000,0.000000,0.000000,...,0.693147,0.000000,1.791759,2.944439,2.772589,0.693147,0.000000,2.302585,1.609438,1.386294
1,0.000000,0.000000,0.000000,0.000000,3.258097,0.693147,0.0,0.000000,0.693147,0.000000,...,0.000000,0.693147,1.386294,0.000000,0.000000,0.000000,0.000000,2.079442,1.945910,0.693147
2,0.000000,0.693147,0.693147,0.693147,3.367296,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.693147,1.791759,3.433987,3.433987,0.693147,0.000000,2.302585,1.609438,2.197225
3,0.000000,0.693147,0.000000,0.693147,3.332205,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.484907,1.386294,1.945910
4,0.000000,0.693147,0.693147,0.693147,3.218876,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,1.386294,0.000000,0.000000,0.000000,2.484907,1.791759,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.000000,0.693147,0.693147,0.693147,3.828641,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,1.791759,0.000000,0.693147,1.791759,1.945910,2.079442
253676,0.000000,0.693147,0.693147,0.693147,2.944439,0.000000,0.0,1.098612,0.000000,0.000000,...,0.693147,0.000000,1.609438,0.000000,0.000000,0.693147,0.000000,2.484907,1.098612,1.609438
253677,0.000000,0.000000,0.000000,0.693147,3.367296,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,1.098612,1.791759,1.098612
253678,0.000000,0.693147,0.000000,0.693147,3.178054,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,0.000000,0.000000,0.693147,2.079442,1.791759,0.693147
253679,0.693147,0.693147,0.693147,0.693147,3.258097,0.000000,0.0,1.098612,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.302585,1.945910,1.098612

In [14]:
KBinsDiscretizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0,2,2,2,0,2,0,0,0,0,...,2,0,2,1,1,2,0,2,1,0
1,0,0,0,0,0,2,0,0,2,0,...,0,2,1,0,0,0,0,1,2,0
2,0,2,2,2,0,0,0,0,0,2,...,2,2,2,2,2,2,0,2,1,2
3,0,2,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,1,2
4,0,2,2,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,2,2,2,1,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,2
253676,0,2,2,2,0,0,0,2,0,0,...,2,0,2,0,0,2,0,2,0,1
253677,0,0,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,0,2,0
253678,0,2,0,2,0,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,0
253679,2,2,2,2,0,0,0,2,2,2,...,2,0,0,0,0,0,0,2,2,0

In [15]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = cp.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = cp.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = cp.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = cp.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = cp.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = cp.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = cudf.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        self.generating_data()
        self.generating_dataframe()

In [16]:
gen_df = Data_Generation(df, 10000000, float)

In [17]:
gen_df.main()

In [18]:
generated_data_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,0.0,0.0,83.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,4.0,0.0,0.0,1.0,1.0,10.0,3.0,1.0
1,0.0,1.0,0.0,64.0,1.0,0.0,2.0,1.0,0.0,1.0,...,0.0,1.0,5.0,2.0,26.0,0.0,1.0,3.0,4.0,1.0
2,1.0,1.0,0.0,54.0,1.0,1.0,2.0,0.0,1.0,1.0,...,0.0,1.0,2.0,1.0,23.0,0.0,0.0,7.0,2.0,4.0
3,1.0,0.0,0.0,73.0,1.0,0.0,2.0,1.0,1.0,0.0,...,0.0,0.0,2.0,27.0,11.0,1.0,0.0,1.0,6.0,2.0
4,1.0,0.0,1.0,21.0,1.0,1.0,2.0,0.0,0.0,1.0,...,0.0,1.0,5.0,23.0,21.0,1.0,0.0,3.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,30.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,1.0,5.0,5.0,0.0,1.0,1.0,13.0,6.0,6.0
9999996,0.0,0.0,0.0,20.0,1.0,1.0,2.0,0.0,1.0,1.0,...,0.0,1.0,3.0,30.0,13.0,0.0,0.0,1.0,1.0,1.0
9999997,1.0,0.0,0.0,89.0,0.0,1.0,2.0,0.0,0.0,1.0,...,1.0,0.0,4.0,21.0,3.0,0.0,1.0,10.0,5.0,8.0
9999998,1.0,0.0,1.0,41.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,20.0,5.0,1.0,0.0,1.0,3.0,4.0
9999999,0.0,0.0,0.0,28.0,1.0,1.0,2.0,1.0,1.0,1.0,...,0.0,0.0,3.0,6.0,29.0,1.0,1.0,1.0,6.0,4.0

In [19]:
norm_gen_data = Normalization(generated_data_global)

In [20]:
norm_gen_data.main()

Execution time: 8.76252031326294 seconds

In [21]:
maxAbsScaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,0.0,0.0,0.846939,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.8,0.000000,0.000000,1.0,1.0,0.769231,0.500000,0.125
1,0.0,1.0,0.0,0.653061,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.066667,0.866667,0.0,1.0,0.230769,0.666667,0.125
2,1.0,1.0,0.0,0.551020,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.4,0.033333,0.766667,0.0,0.0,0.538462,0.333333,0.500
3,1.0,0.0,0.0,0.744898,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.4,0.900000,0.366667,1.0,0.0,0.076923,1.000000,0.250
4,1.0,0.0,1.0,0.214286,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.766667,0.700000,1.0,0.0,0.230769,0.333333,0.125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,0.306122,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.166667,0.000000,1.0,1.0,1.000000,1.000000,0.750
9999996,0.0,0.0,0.0,0.204082,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.6,1.000000,0.433333,0.0,0.0,0.076923,0.166667,0.125
9999997,1.0,0.0,0.0,0.908163,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.8,0.700000,0.100000,0.0,1.0,0.769231,0.833333,1.000
9999998,1.0,0.0,1.0,0.418367,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.666667,0.166667,1.0,0.0,0.076923,0.500000,0.500
9999999,0.0,0.0,0.0,0.285714,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.6,0.200000,0.966667,1.0,1.0,0.076923,1.000000,0.500

In [22]:
MinMaxScaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,0.0,0.0,0.825581,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.75,0.000000,0.000000,1.0,1.0,0.750000,0.4,0.000000
1,0.0,1.0,0.0,0.604651,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.00,0.066667,0.866667,0.0,1.0,0.166667,0.6,0.000000
2,1.0,1.0,0.0,0.488372,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.25,0.033333,0.766667,0.0,0.0,0.500000,0.2,0.428571
3,1.0,0.0,0.0,0.709302,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.25,0.900000,0.366667,1.0,0.0,0.000000,1.0,0.142857
4,1.0,0.0,1.0,0.104651,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.00,0.766667,0.700000,1.0,0.0,0.166667,0.2,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,0.209302,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.00,0.166667,0.000000,1.0,1.0,1.000000,1.0,0.714286
9999996,0.0,0.0,0.0,0.093023,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.50,1.000000,0.433333,0.0,0.0,0.000000,0.0,0.000000
9999997,1.0,0.0,0.0,0.895349,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.75,0.700000,0.100000,0.0,1.0,0.750000,0.8,1.000000
9999998,1.0,0.0,1.0,0.337209,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.00,0.666667,0.166667,1.0,0.0,0.000000,0.4,0.428571
9999999,0.0,0.0,0.0,0.186047,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.50,0.200000,0.966667,1.0,1.0,0.000000,1.0,0.428571

In [23]:
normalizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.000000,0.000000,0.000000,0.990626,0.000000,0.000000,0.000000,0.011935,0.000000,0.000000,...,0.000000,0.011935,0.047741,0.000000,0.000000,0.011935,0.011935,0.119352,0.035806,0.011935
1,0.000000,0.014378,0.000000,0.920221,0.014378,0.000000,0.028757,0.014378,0.000000,0.014378,...,0.000000,0.014378,0.071892,0.028757,0.373840,0.000000,0.014378,0.043135,0.057514,0.014378
2,0.016831,0.016831,0.000000,0.908880,0.016831,0.016831,0.033662,0.000000,0.016831,0.016831,...,0.000000,0.016831,0.033662,0.016831,0.387115,0.000000,0.000000,0.117818,0.033662,0.067324
3,0.012665,0.000000,0.000000,0.924569,0.012665,0.000000,0.025331,0.012665,0.012665,0.000000,...,0.000000,0.000000,0.025331,0.341964,0.139319,0.012665,0.000000,0.012665,0.075992,0.025331
4,0.026153,0.000000,0.026153,0.549219,0.026153,0.026153,0.052307,0.000000,0.000000,0.026153,...,0.000000,0.026153,0.130766,0.601526,0.549219,0.026153,0.000000,0.078460,0.052307,0.026153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,0.028808,0.000000,0.028808,0.864227,0.028808,0.028808,0.057615,0.000000,0.028808,0.000000,...,0.028808,0.028808,0.144038,0.144038,0.000000,0.028808,0.028808,0.374498,0.172845,0.172845
9999996,0.000000,0.000000,0.000000,0.518128,0.025906,0.025906,0.051813,0.000000,0.025906,0.025906,...,0.000000,0.025906,0.077719,0.777192,0.336783,0.000000,0.000000,0.025906,0.025906,0.025906
9999997,0.010793,0.000000,0.000000,0.960550,0.000000,0.010793,0.021585,0.000000,0.000000,0.010793,...,0.010793,0.000000,0.043171,0.226647,0.032378,0.000000,0.010793,0.107927,0.053963,0.086342
9999998,0.021502,0.000000,0.021502,0.881568,0.000000,0.000000,0.000000,0.000000,0.000000,0.021502,...,0.021502,0.000000,0.107508,0.430033,0.107508,0.021502,0.000000,0.021502,0.064505,0.086007
9999999,0.000000,0.000000,0.000000,0.672215,0.024008,0.024008,0.048015,0.024008,0.024008,0.024008,...,0.000000,0.000000,0.072023,0.144046,0.696223,0.024008,0.024008,0.024008,0.144046,0.096031

In [24]:
robust_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,-1.0,0.0,0.636364,-1.0,-1.0,-0.5,1.0,0.0,0.0,...,-1.0,1.0,0.5,-0.9375,-0.9375,0.0,0.0,0.500000,-0.333333,-0.8
1,0.0,0.0,0.0,0.204545,0.0,-1.0,0.5,1.0,0.0,1.0,...,-1.0,1.0,1.0,-0.8125,0.6875,-1.0,0.0,-0.666667,0.000000,-0.8
2,1.0,0.0,0.0,-0.022727,0.0,0.0,0.5,0.0,1.0,1.0,...,-1.0,1.0,-0.5,-0.8750,0.5000,-1.0,-1.0,0.000000,-0.666667,-0.2
3,1.0,-1.0,0.0,0.409091,0.0,-1.0,0.5,1.0,1.0,0.0,...,-1.0,0.0,-0.5,0.7500,-0.2500,0.0,-1.0,-1.000000,0.666667,-0.6
4,1.0,-1.0,1.0,-0.772727,0.0,0.0,0.5,0.0,0.0,1.0,...,-1.0,1.0,1.0,0.5000,0.3750,0.0,-1.0,-0.666667,-0.666667,-0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,-1.0,1.0,-0.568182,0.0,0.0,0.5,0.0,1.0,0.0,...,0.0,1.0,1.0,-0.6250,-0.9375,0.0,0.0,1.000000,0.666667,0.2
9999996,0.0,-1.0,0.0,-0.795455,0.0,0.0,0.5,0.0,1.0,1.0,...,-1.0,1.0,0.0,0.9375,-0.1250,-1.0,-1.0,-1.000000,-1.000000,-0.8
9999997,1.0,-1.0,0.0,0.772727,-1.0,0.0,0.5,0.0,0.0,1.0,...,0.0,0.0,0.5,0.3750,-0.7500,-1.0,0.0,0.500000,0.333333,0.6
9999998,1.0,-1.0,1.0,-0.318182,-1.0,-1.0,-0.5,0.0,0.0,1.0,...,0.0,0.0,1.0,0.3125,-0.6250,0.0,-1.0,-1.000000,-0.333333,-0.2
9999999,0.0,-1.0,0.0,-0.613636,0.0,0.0,0.5,1.0,1.0,1.0,...,-1.0,0.0,0.0,-0.5625,0.8750,0.0,0.0,-1.000000,0.666667,-0.2

In [25]:
standard_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,-0.999983,-1.000289,-0.999852,1.114585,-1.00039,-1.00032,-1.224273,1.000176,-0.999626,-0.999149,...,-1.000128,1.000479,0.707268,-1.676843,-1.676895,0.999963,0.999649,0.802070,-0.292798,-1.527377
1,-0.999983,0.999711,-0.999852,0.358079,0.99961,-1.00032,1.225053,1.000176,-0.999626,1.000852,...,-1.000128,1.000479,1.414173,-1.453263,1.229542,-1.000037,0.999649,-1.068639,0.292729,-1.527377
2,1.000017,0.999711,-0.999852,-0.040083,0.99961,0.99968,1.225053,-0.999824,1.000374,1.000852,...,-1.000128,1.000479,-0.706541,-1.565053,0.894184,-1.000037,-1.000351,0.000338,-0.878325,-0.218314
3,1.000017,-1.000289,-0.999852,0.716424,0.99961,-1.00032,1.225053,1.000176,1.000374,-0.999149,...,-1.000128,-0.999522,-0.706541,1.341496,-0.447249,0.999963,-1.000351,-1.603127,1.463783,-1.091023
4,1.000017,-1.000289,1.000148,-1.354016,0.99961,0.99968,1.225053,-0.999824,-0.999626,1.000852,...,-1.000128,1.000479,1.414173,0.894335,0.670612,0.999963,-1.000351,-1.068639,-0.878325,-1.527377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.000017,-1.000289,1.000148,-0.995670,0.99961,0.99968,1.225053,-0.999824,1.000374,-0.999149,...,0.999872,1.000479,1.414173,-1.117891,-1.676895,0.999963,0.999649,1.603803,1.463783,0.654395
9999996,-0.999983,-1.000289,-0.999852,-1.393832,0.99961,0.99968,1.225053,-0.999824,1.000374,1.000852,...,-1.000128,1.000479,0.000364,1.676867,-0.223676,-1.000037,-1.000351,-1.603127,-1.463852,-1.527377
9999997,1.000017,-1.000289,-0.999852,1.353482,-1.00039,0.99968,1.225053,-0.999824,-0.999626,1.000852,...,0.999872,-0.999522,0.707268,0.670754,-1.341537,-1.000037,0.999649,0.802070,0.878256,1.527103
9999998,1.000017,-1.000289,1.000148,-0.557693,-1.00039,-1.00032,-1.224273,-0.999824,-0.999626,1.000852,...,0.999872,-0.999522,1.414173,0.558964,-1.117965,0.999963,-1.000351,-1.603127,-0.292798,-0.218314
9999999,-0.999983,-1.000289,-0.999852,-1.075303,0.99961,0.99968,1.225053,1.000176,1.000374,1.000852,...,-1.000128,-0.999522,0.000364,-1.006101,1.564900,0.999963,0.999649,-1.603127,1.463783,-0.218314

In [26]:
binarizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
2,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0
3,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
4,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
9999996,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0
9999997,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
9999998,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
9999999,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [27]:
function_transformer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.000000,0.000000,0.000000,4.430817,0.000000,0.000000,0.000000,0.693147,0.000000,0.000000,...,0.000000,0.693147,1.609438,0.000000,0.000000,0.693147,0.693147,2.397895,1.386294,0.693147
1,0.000000,0.693147,0.000000,4.174387,0.693147,0.000000,1.098612,0.693147,0.000000,0.693147,...,0.000000,0.693147,1.791759,1.098612,3.295837,0.000000,0.693147,1.386294,1.609438,0.693147
2,0.693147,0.693147,0.000000,4.007333,0.693147,0.693147,1.098612,0.000000,0.693147,0.693147,...,0.000000,0.693147,1.098612,0.693147,3.178054,0.000000,0.000000,2.079442,1.098612,1.609438
3,0.693147,0.000000,0.000000,4.304065,0.693147,0.000000,1.098612,0.693147,0.693147,0.000000,...,0.000000,0.000000,1.098612,3.332205,2.484907,0.693147,0.000000,0.693147,1.945910,1.098612
4,0.693147,0.000000,0.693147,3.091042,0.693147,0.693147,1.098612,0.000000,0.000000,0.693147,...,0.000000,0.693147,1.791759,3.178054,3.091042,0.693147,0.000000,1.386294,1.098612,0.693147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,0.693147,0.000000,0.693147,3.433987,0.693147,0.693147,1.098612,0.000000,0.693147,0.000000,...,0.693147,0.693147,1.791759,1.791759,0.000000,0.693147,0.693147,2.639057,1.945910,1.945910
9999996,0.000000,0.000000,0.000000,3.044522,0.693147,0.693147,1.098612,0.000000,0.693147,0.693147,...,0.000000,0.693147,1.386294,3.433987,2.639057,0.000000,0.000000,0.693147,0.693147,0.693147
9999997,0.693147,0.000000,0.000000,4.499810,0.000000,0.693147,1.098612,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.609438,3.091042,1.386294,0.000000,0.693147,2.397895,1.791759,2.197225
9999998,0.693147,0.000000,0.693147,3.737670,0.000000,0.000000,0.000000,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.791759,3.044522,1.791759,0.693147,0.000000,0.693147,1.386294,1.609438
9999999,0.000000,0.000000,0.000000,3.367296,0.693147,0.693147,1.098612,0.693147,0.693147,0.693147,...,0.000000,0.000000,1.386294,1.945910,3.401197,0.693147,0.693147,0.693147,1.945910,1.609438

In [28]:
KBinsDiscretizer_global

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0,0,0,2,0,0,0,2,0,0,...,0,2,2,0,0,2,2,2,1,0
1,0,2,0,1,2,0,2,2,0,2,...,0,2,2,0,2,0,2,0,1,0
2,2,2,0,1,2,2,2,0,2,2,...,0,2,0,0,2,0,0,1,0,1
3,2,0,0,2,2,0,2,2,2,0,...,0,0,0,2,1,2,0,0,2,0
4,2,0,2,0,2,2,2,0,0,2,...,0,2,2,2,2,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,2,0,2,0,2,2,2,0,2,0,...,2,2,2,0,0,2,2,2,2,2
9999996,0,0,0,0,2,2,2,0,2,2,...,0,2,1,2,1,0,0,0,0,0
9999997,2,0,0,2,0,2,2,0,0,2,...,2,0,2,2,0,0,2,2,2,2
9999998,2,0,2,1,0,0,0,0,0,2,...,2,0,2,2,0,2,0,0,1,1
9999999,0,0,0,0,2,2,2,2,2,2,...,0,0,1,0,2,2,2,0,2,1

In [29]:
from cuml import LinearRegression
from cuml.linear_model import LinearRegression

In [30]:
lr = LinearRegression(fit_intercept = True, algorithm = "eig")
X = cudf.DataFrame(df.copy().drop(['HeartDiseaseorAttack'], axis = 1))
y = cudf.DataFrame(df['HeartDiseaseorAttack'].copy())

In [31]:
reg = lr.fit(X,y)
print(reg.coef_)

0     0.033506
1     0.038606
2     0.014458
3    -0.001249
4     0.023006
5     0.187874
6     0.023933
7     0.003166
8     0.003848
9     0.003523
10   -0.019211
11    0.008023
12    0.007689
13    0.032988
14   -0.000184
15    0.000954
16    0.049835
17    0.053135
18    0.011045
19    0.001019
20   -0.003531
dtype: float64

In [32]:
print(reg.intercept_)

-0.14540693374116526

In [33]:
X_gen = cudf.DataFrame(generated_data_global.copy())
preds = lr.predict(X_gen)
print(preds)

0          0.087429
1          0.174677
2          0.286006
3         -0.012993
4          0.389297
             ...
9999995    0.519673
9999996    0.217803
9999997    0.295571
9999998    0.059513
9999999    0.301215
Length: 10000000, dtype: float64

In [34]:
X = cudf.DataFrame(df.copy().drop(['HeartDiseaseorAttack'], axis = 1))
y = df['HeartDiseaseorAttack'].copy().to_numpy()
model = cuml.LogisticRegression().fit(X, y)
print(model.coef_)

         0         1         2         3         4         5         6   \
0  0.529062  0.615359  0.499786  0.000518  0.362985  0.977776  0.146363

         7         8         9   ...       11       12        13        14  \
0  0.039248  0.006029  0.041693  ... -0.03202  0.25527  0.487786  0.002375

         15        16        17        18        19        20
0  0.001085  0.298526  0.759769  0.254522  0.009098 -0.043229

[1 rows x 21 columns]

In [35]:
print(model.intercept_)

0   -7.825065
dtype: float64

In [36]:
X_gen = cudf.DataFrame(generated_data_global.copy())
preds = model.predict(X_gen)
print(preds)

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
          ...
9999995    1.0
9999996    0.0
9999997    0.0
9999998    0.0
9999999    0.0
Length: 10000000, dtype: float64