In [1]:
!lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.4 LTS
Release:	24.04
Codename:	noble

In [2]:
import pandas as pd
import cupy as cp
import cudf
import cuml

In [3]:
df = cudf.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [4]:
from cuml.preprocessing import MaxAbsScaler
from cuml.preprocessing import MinMaxScaler
from cuml.preprocessing import Normalizer
from cuml.preprocessing import RobustScaler
from cuml.preprocessing import StandardScaler
from cuml.preprocessing import Binarizer
from cuml.preprocessing import FunctionTransformer
from cuml.preprocessing import KBinsDiscretizer
import cupy as cp
import time

In [5]:
class Normalization(object):
    def __init__(self, dataset):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_numpy_array = self.dataset.copy().to_numpy()
        self.X = cp.array(self.dataset_numpy_array)


    def MaxAbsScaler(self):
        global maxAbsScaler_global

        transformer = MaxAbsScaler().fit(self.X)
        df_maxAbs_scaler_transform = transformer.transform(self.X)
        
        maxAbsScaler_global = cudf.DataFrame(df_maxAbs_scaler_transform)
    
    def MinMaxScaler(self):
        global MinMaxScaler_global

        transformer = MinMaxScaler().fit(self.X)
        df_MinMaxScaler_transform = transformer.transform(self.X)

        MinMaxScaler_global = cudf.DataFrame(df_MinMaxScaler_transform)

    def Normalizer(self):
        global normalizer_global

        transformer = Normalizer().fit(self.X)
        df_normalizer_transform = transformer.transform(self.X)

        normalizer_global = cudf.DataFrame(df_normalizer_transform)

    def RobustScaler(self):
        global robust_scaler_global

        transformer = RobustScaler().fit(self.X)
        df_robust_scaler_transform = transformer.transform(self.X)

        robust_scaler_global = cudf.DataFrame(df_robust_scaler_transform)

    def StandardScaler(self):
        global standard_scaler_global

        transformer = StandardScaler().fit(self.X)
        df_standard_scaler_transform = transformer.transform(self.X)

        standard_scaler_global = cudf.DataFrame(df_standard_scaler_transform)

    def Binarizer(self):
        global binarizer_global

        transformer = Binarizer().fit(self.X)
        df_binarizer_transform = transformer.transform(self.X)

        binarizer_global = cudf.DataFrame(df_binarizer_transform)

    def FunctionTransformer(self):
        global function_transformer_global

        transformer = FunctionTransformer(func=cp.log1p)
        df_function_transformer_transform = transformer.transform(self.X)

        function_transformer_global = cudf.DataFrame(df_function_transformer_transform)

    def KBinsDiscretizer(self):
        global KBinsDiscretizer_global

        transformer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit(self.X)
        df_KBinsDiscretizer_transform = transformer.transform(self.X)

        KBinsDiscretizer_global = cudf.DataFrame(df_KBinsDiscretizer_transform)


    def main(self):
        st = time.time()
        self.MaxAbsScaler()
        self.MinMaxScaler()
        self.Normalizer()
        self.RobustScaler()
        self.StandardScaler()
        self.Binarizer()
        self.FunctionTransformer()
        self.KBinsDiscretizer()

        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [6]:
norm = Normalization(df)

In [7]:
norm.main()

Execution time: 0.7174539566040039 seconds

In [8]:
maxAbsScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375
1,0.0,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125
2,0.0,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000
3,0.0,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750
4,0.0,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875
253676,0.0,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500
253677,0.0,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250
253678,0.0,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125
253679,1.0,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250

In [9]:
MinMaxScaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,0.325581,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.00,0.6,0.500000,1.0,0.0,0.666667,0.6,0.285714
1,0.0,0.0,0.0,0.0,0.151163,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.50,0.0,0.000000,0.0,0.0,0.500000,1.0,0.000000
2,0.0,1.0,1.0,1.0,0.186047,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.00,1.0,1.000000,1.0,0.0,0.666667,0.6,1.000000
3,0.0,1.0,0.0,1.0,0.174419,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.833333,0.4,0.714286
4,0.0,1.0,1.0,1.0,0.139535,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.1,0.000000,0.0,0.0,0.833333,0.8,0.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.383721,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.166667,0.0,1.0,0.333333,1.0,0.857143
253676,0.0,1.0,1.0,1.0,0.069767,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.75,0.0,0.000000,1.0,0.0,0.833333,0.2,0.428571
253677,0.0,0.0,0.0,1.0,0.186047,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.083333,0.8,0.142857
253678,0.0,1.0,0.0,1.0,0.127907,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.000000,0.0,1.0,0.500000,0.8,0.000000
253679,1.0,1.0,1.0,1.0,0.151163,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.666667,1.0,0.142857

In [10]:
normalizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.00000,0.020911,0.020911,0.020911,0.836425,0.020911,0.0,0.000000,0.000000,0.000000,...,0.020911,0.000000,0.104553,0.376391,0.313659,0.020911,0.000000,0.188196,0.083642,0.062732
1,0.00000,0.000000,0.000000,0.000000,0.929760,0.037190,0.0,0.000000,0.037190,0.000000,...,0.000000,0.037190,0.111571,0.000000,0.000000,0.000000,0.000000,0.260333,0.223142,0.037190
2,0.00000,0.018976,0.018976,0.018976,0.531337,0.000000,0.0,0.000000,0.000000,0.018976,...,0.018976,0.018976,0.094882,0.569290,0.569290,0.018976,0.000000,0.170787,0.075905,0.151811
3,0.00000,0.033241,0.000000,0.033241,0.897510,0.000000,0.0,0.000000,0.033241,0.033241,...,0.033241,0.000000,0.066482,0.000000,0.000000,0.000000,0.000000,0.365652,0.099723,0.199447
4,0.00000,0.036322,0.036322,0.036322,0.871719,0.000000,0.0,0.000000,0.036322,0.036322,...,0.036322,0.000000,0.072643,0.108965,0.000000,0.000000,0.000000,0.399538,0.181608,0.145287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.00000,0.021437,0.021437,0.021437,0.964680,0.000000,0.0,0.000000,0.000000,0.021437,...,0.021437,0.000000,0.064312,0.000000,0.107187,0.000000,0.021437,0.107187,0.128624,0.150061
253676,0.00000,0.045175,0.045175,0.045175,0.813157,0.000000,0.0,0.090351,0.000000,0.000000,...,0.045175,0.000000,0.180702,0.000000,0.000000,0.045175,0.000000,0.496929,0.090351,0.180702
253677,0.00000,0.000000,0.000000,0.034879,0.976612,0.000000,0.0,0.000000,0.034879,0.034879,...,0.034879,0.000000,0.034879,0.000000,0.000000,0.000000,0.000000,0.069758,0.174395,0.069758
253678,0.00000,0.040193,0.000000,0.040193,0.924448,0.000000,0.0,0.000000,0.000000,0.040193,...,0.040193,0.000000,0.120580,0.000000,0.000000,0.000000,0.040193,0.281354,0.200967,0.040193
253679,0.03625,0.036250,0.036250,0.036250,0.906249,0.000000,0.0,0.072500,0.036250,0.036250,...,0.036250,0.000000,0.072500,0.000000,0.000000,0.000000,0.000000,0.326250,0.217500,0.072500

In [11]:
robust_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,0.0,1.857143,1.0,0.0,0.0,-1.0,-1.0,...,0.0,0.0,3.0,9.0,5.000000,1.0,0.0,0.25,-0.5,-1.333333
1,0.0,0.0,0.0,-1.0,-0.285714,1.0,0.0,0.0,0.0,-1.0,...,-1.0,1.0,1.0,0.0,0.000000,0.0,0.0,-0.25,0.5,-2.000000
2,0.0,1.0,1.0,0.0,0.142857,0.0,0.0,0.0,-1.0,0.0,...,0.0,1.0,3.0,15.0,10.000000,1.0,0.0,0.25,-0.5,0.333333
3,0.0,1.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.75,-1.0,-0.333333
4,0.0,1.0,1.0,0.0,-0.428571,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.5,0.000000,0.0,0.0,0.75,0.0,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,0.0,2.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,1.666667,0.0,1.0,-0.75,0.5,0.000000
253676,0.0,1.0,1.0,0.0,-1.285714,0.0,0.0,2.0,-1.0,-1.0,...,0.0,0.0,2.0,0.0,0.000000,1.0,0.0,0.75,-1.5,-1.000000
253677,0.0,0.0,0.0,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,0.0,0.000000,0.0,0.0,-1.50,0.0,-1.666667
253678,0.0,1.0,0.0,0.0,-0.571429,0.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,1.0,0.0,0.000000,0.0,1.0,-0.25,0.0,-2.000000
253679,1.0,1.0,1.0,0.0,-0.285714,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.25,0.5,-1.666667

In [12]:
standard_scaler_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-0.322458,1.153688,1.165254,0.196922,1.757936,1.120927,-0.205637,-0.425292,-1.762814,-1.316872,...,0.226863,-0.303173,2.329121,1.998592,1.233999,2.223615,-0.887021,0.316900,-1.065595,-1.474487
1,-0.322458,-0.866785,-0.858182,-5.078164,-0.511806,1.120927,-0.205637,-0.425292,0.567275,-1.316872,...,-4.407954,3.298445,0.457294,-0.429630,-0.486592,-0.449718,-0.887021,-0.337933,0.963272,-2.440138
2,-0.322458,1.153688,1.165254,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,3.298445,2.329121,3.617407,2.954590,2.223615,-0.887021,0.316900,-1.065595,0.939638
3,-0.322458,1.153688,-0.858182,0.196922,-0.209174,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.971733,-2.080028,-0.026012
4,-0.322458,1.153688,1.165254,0.196922,-0.663122,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.024926,-0.486592,-0.449718,-0.887021,0.971733,-0.051162,-0.991662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,-0.322458,1.153688,1.165254,0.196922,2.514516,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,0.086938,-0.449718,1.127369,-0.992766,0.963272,0.456813
253676,-0.322458,1.153688,1.165254,0.196922,-1.571019,-0.892119,-0.205637,2.439387,-1.762814,-1.316872,...,0.226863,-0.303173,1.393207,-0.429630,-0.486592,2.223615,-0.887021,0.971733,-3.094461,-0.991662
253677,-0.322458,-0.866785,-0.858182,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,0.567275,0.759375,...,0.226863,-0.303173,-1.414532,-0.429630,-0.486592,-0.449718,-0.887021,-1.975015,-0.051162,-1.957312
253678,-0.322458,1.153688,-0.858182,0.196922,-0.814438,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,...,0.226863,-0.303173,0.457294,-0.429630,-0.486592,-0.449718,1.127369,-0.337933,-0.051162,-2.440138
253679,3.101183,1.153688,1.165254,0.196922,-0.511806,-0.892119,-0.205637,2.439387,0.567275,0.759375,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.316900,0.963272,-1.957312

In [13]:
binarizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0
253676,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0
253677,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
253678,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
253679,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0

In [14]:
function_transformer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.000000,0.693147,0.693147,0.693147,3.713572,0.693147,0.0,0.000000,0.000000,0.000000,...,0.693147,0.000000,1.791759,2.944439,2.772589,0.693147,0.000000,2.302585,1.609438,1.386294
1,0.000000,0.000000,0.000000,0.000000,3.258097,0.693147,0.0,0.000000,0.693147,0.000000,...,0.000000,0.693147,1.386294,0.000000,0.000000,0.000000,0.000000,2.079442,1.945910,0.693147
2,0.000000,0.693147,0.693147,0.693147,3.367296,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.693147,1.791759,3.433987,3.433987,0.693147,0.000000,2.302585,1.609438,2.197225
3,0.000000,0.693147,0.000000,0.693147,3.332205,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.484907,1.386294,1.945910
4,0.000000,0.693147,0.693147,0.693147,3.218876,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,1.098612,1.386294,0.000000,0.000000,0.000000,2.484907,1.791759,1.609438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.000000,0.693147,0.693147,0.693147,3.828641,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,1.791759,0.000000,0.693147,1.791759,1.945910,2.079442
253676,0.000000,0.693147,0.693147,0.693147,2.944439,0.000000,0.0,1.098612,0.000000,0.000000,...,0.693147,0.000000,1.609438,0.000000,0.000000,0.693147,0.000000,2.484907,1.098612,1.609438
253677,0.000000,0.000000,0.000000,0.693147,3.367296,0.000000,0.0,0.000000,0.693147,0.693147,...,0.693147,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,1.098612,1.791759,1.098612
253678,0.000000,0.693147,0.000000,0.693147,3.178054,0.000000,0.0,0.000000,0.000000,0.693147,...,0.693147,0.000000,1.386294,0.000000,0.000000,0.000000,0.693147,2.079442,1.791759,0.693147
253679,0.693147,0.693147,0.693147,0.693147,3.258097,0.000000,0.0,1.098612,0.693147,0.693147,...,0.693147,0.000000,1.098612,0.000000,0.000000,0.000000,0.000000,2.302585,1.945910,1.098612

In [15]:
KBinsDiscretizer_global

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0,2,2,2,0,2,0,0,0,0,...,2,0,2,1,1,2,0,2,1,0
1,0,0,0,0,0,2,0,0,2,0,...,0,2,1,0,0,0,0,1,2,0
2,0,2,2,2,0,0,0,0,0,2,...,2,2,2,2,2,2,0,2,1,2
3,0,2,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,1,2
4,0,2,2,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,2,2,2,1,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,2
253676,0,2,2,2,0,0,0,2,0,0,...,2,0,2,0,0,2,0,2,0,1
253677,0,0,0,2,0,0,0,0,2,2,...,2,0,0,0,0,0,0,0,2,0
253678,0,2,0,2,0,0,0,0,0,2,...,2,0,1,0,0,0,2,1,2,0
253679,2,2,2,2,0,0,0,2,2,2,...,2,0,0,0,0,0,0,2,2,0

In [16]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = cp.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = cp.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = cp.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = cp.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = cp.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = cp.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = cudf.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        self.generating_data()
        self.generating_dataframe()

In [17]:
gen_df = Data_Generation(df, 10000000, float)

In [18]:
gen_df.main()

In [19]:
generated_data_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,18.0,26.0,0.0,0.0,2.0,1.0,5.0
1,0.0,0.0,1.0,67.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,3.0,27.0,3.0,1.0,0.0,3.0,1.0,8.0
2,0.0,1.0,0.0,57.0,0.0,1.0,2.0,0.0,0.0,1.0,...,0.0,1.0,5.0,28.0,21.0,1.0,0.0,9.0,2.0,4.0
3,1.0,0.0,0.0,88.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,2.0,4.0,30.0,1.0,1.0,4.0,4.0,3.0
4,1.0,1.0,1.0,76.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,27.0,2.0,1.0,1.0,5.0,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.0,0.0,0.0,97.0,0.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,5.0,24.0,29.0,1.0,1.0,4.0,2.0,2.0
9999996,0.0,0.0,1.0,42.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,13.0,28.0,0.0,0.0,10.0,3.0,5.0
9999997,0.0,0.0,1.0,82.0,0.0,1.0,0.0,0.0,1.0,1.0,...,1.0,1.0,2.0,29.0,9.0,1.0,1.0,13.0,2.0,5.0
9999998,1.0,1.0,0.0,22.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,4.0,30.0,23.0,0.0,1.0,9.0,3.0,3.0
9999999,0.0,0.0,0.0,18.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,13.0,3.0,1.0,0.0,13.0,6.0,8.0

In [20]:
norm_gen_data = Normalization(generated_data_global)

In [21]:
norm_gen_data.main()

MemoryError: std::bad_alloc: out_of_memory: CUDA error (failed to allocate 1680000000 bytes) at: /tmp/pip-build-env-5adu7k8c/normal/lib/python3.12/site-packages/librmm/include/rmm/mr/cuda_memory_resource.hpp:51: cudaErrorMemoryAllocation out of memory

In [ ]:
maxAbsScaler_global

In [ ]:
MinMaxScaler_global

In [ ]:
normalizer_global

In [ ]:
robust_scaler_global

In [ ]:
standard_scaler_global

In [ ]:
binarizer_global

In [ ]:
function_transformer_global

In [ ]:
KBinsDiscretizer_global

In [ ]:
from cuml import LinearRegression
from cuml.linear_model import LinearRegression

In [ ]:
lr = LinearRegression(fit_intercept = True, algorithm = "eig")
X = cudf.DataFrame(df.copy().drop(['HeartDiseaseorAttack'], axis = 1))
y = cudf.DataFrame(df['HeartDiseaseorAttack'].copy())

In [ ]:
reg = lr.fit(X,y)
print(reg.coef_)

In [ ]:
print(reg.intercept_)

In [ ]:
X_gen = cudf.DataFrame(generated_data_global.copy())
preds = lr.predict(X_gen)
print(preds)

In [ ]:
X = cudf.DataFrame(df.copy().drop(['HeartDiseaseorAttack'], axis = 1))
y = df['HeartDiseaseorAttack'].copy().to_numpy()
model = cuml.LogisticRegression().fit(X, y)
print(model.coef_)

In [ ]:
print(model.intercept_)

In [ ]:
X_gen = cudf.DataFrame(generated_data_global.copy())
preds = model.predict(X_gen)
print(preds)